language: python
python:
 - 3.6
install:
 - cp contrib/env-sample .env
 - pip install -q -r requirements-dev.txt codecov
script:
 - isort --recursive --check-only --diff charcoallog
 - flake8 .
 - coverage run manage.py test
 - coverage report
after_success:
 - codecov

