language: python
python:
 - 3.6
install:
 - cp contrib/env-sample .env
 - pip install -q -r requirements-dev.txt codecov
script:
 - flake8
 - coverage run manage.py test -t ./
 - coverage report
after_success:
 - codecov

